TIMIDITY_OBJS = \
	common.o \
	instrum.o \
	mix.o \
	output.o \
	playmidi.o \
	readmidi.o \
	resample.o \
	stream.o \
	tables.o \
	timidity.o

TIMIDITY_PATH = libs/timidity/src

OBJS += $(addprefix $(TIMIDITY_PATH)/,$(TIMIDITY_OBJS))
