/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_simusplayer_NativeInterface */

#ifndef _Included_xtvapps_simusplayer_NativeInterface
#define _Included_xtvapps_simusplayer_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xtvapps_simusplayer_NativeInterface
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_NativeInterface_init
  (JNIEnv *, jclass);

/*
 * Class:     xtvapps_simusplayer_NativeInterface
 * Method:    dump_ports
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_NativeInterface_dump_1ports
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
