/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_simusplayer_midi_AlsaSequencer */

#ifndef _Included_xtvapps_simusplayer_midi_AlsaSequencer
#define _Included_xtvapps_simusplayer_midi_AlsaSequencer
#ifdef __cplusplus
extern "C" {
#endif
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_NOTEOFF
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_NOTEOFF 7L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_NOTEON
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_NOTEON 6L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_KEYPRESS
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_KEYPRESS 8L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_CONTROLLER
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_CONTROLLER 10L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_PGMCHANGE
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_PGMCHANGE 11L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_CHANPRESS
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_CHANPRESS 12L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_PITCHBEND
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_PITCHBEND 13L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_TEMPO
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_TEMPO 35L
#undef xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_SYSEX
#define xtvapps_simusplayer_midi_AlsaSequencer_SND_SEQ_EVENT_SYSEX 130L
/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaReset
  (JNIEnv *, jclass);

/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaSendEventNote
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaSendEventNote
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaSendEventController
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaSendEventController
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaSendEventChange
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaSendEventChange
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaSendEventPitchBend
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaSendEventPitchBend
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaSendEventSysex
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaSendEventSysex
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     xtvapps_simusplayer_midi_AlsaSequencer
 * Method:    alsaFinish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_midi_AlsaSequencer_alsaFinish
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
