/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_trax_core_GMEPlayer_GMEPlayerListener */

#ifndef _Included_xtvapps_trax_core_GMEPlayer_GMEPlayerListener
#define _Included_xtvapps_trax_core_GMEPlayer_GMEPlayerListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
