/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_simusplayer_core_ModPlayer_ModInfo */

#ifndef _Included_xtvapps_simusplayer_core_ModPlayer_ModInfo
#define _Included_xtvapps_simusplayer_core_ModPlayer_ModInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
