/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_trax_core_ModPlayer_FrameInfo */

#ifndef _Included_xtvapps_trax_core_ModPlayer_FrameInfo
#define _Included_xtvapps_trax_core_ModPlayer_FrameInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
