/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xtvapps_simusplayer_core_FluidPlayer */

#ifndef _Included_xtvapps_simusplayer_core_FluidPlayer
#define _Included_xtvapps_simusplayer_core_FluidPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef xtvapps_simusplayer_core_FluidPlayer_SLEEP_TIME
#define xtvapps_simusplayer_core_FluidPlayer_SLEEP_TIME 10L
/*
 * Class:     xtvapps_simusplayer_core_FluidPlayer
 * Method:    fluidInit
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_xtvapps_simusplayer_core_FluidPlayer_fluidInit
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     xtvapps_simusplayer_core_FluidPlayer
 * Method:    fluidRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xtvapps_simusplayer_core_FluidPlayer_fluidRelease
  (JNIEnv *, jobject);

/*
 * Class:     xtvapps_simusplayer_core_FluidPlayer
 * Method:    fluidFillBuffer
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_xtvapps_simusplayer_core_FluidPlayer_fluidFillBuffer
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
